FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80



# FROM nginx:1.25-alpine

# RUN rm -f /etc/nginx/conf.d/default.conf

# COPY ngnix/nginx.conf /etc/nginx/conf.d/default.conf

# RUN rm -rf /usr/share/nginx/html/*
# COPY --from=builder /app/dist/spa/browser /usr/share/nginx/html

# RUN mkdir -p /var/cache/nginx/client_temp && \
#   chown -R nginx:nginx /var/cache/nginx && \
#   chmod -R 755 /var/cache/nginx

# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]