services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    image: mrseams/kubernetes-scaling-test-backend:latest
    ports:
      - "5000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/db
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    image: mrseams/kubernetes-scaling-test-frontend:latest
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=127.0.0.1:5000/posts
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  mongo-data:
